# SPDX-FileCopyrightText: 2025 National Instruments Corporation
# SPDX-License-Identifier: Apache-2.0
---
num_runs: -1  # Number of iterations the application will run, -1 is infinite

scheduler:
  worker_thread_number: 4
  stop_on_deadlock: true
  stop_on_deadlock_timeout: 500

advanced_network:
  cfg:
    version: 1
    manager: "dpdk"
    master_core: 0  # Master CPU core
    debug: false
    log_level: "info"

    memory_regions:
      # Memory pool for frame headers
      - name: "Headers_RX_CPU"
        kind: "huge"
        affinity: 0
        access:
          - local
        num_bufs: 10000
        # Size of the Ethernet header + IP header + UDP header
        buf_size: 42
      # Memory pool for channel 1 CHDR packet headers
      - name: "CH1_CHDR_Headers_RX_CPU"
        kind: "huge"
        affinity: 0
        access:
          - local
        num_bufs: 10000
        # Size of the CHDR header (depends on CHDR_W size)
        buf_size: 64
      # Memory pool for channel 1 CHDR signal data packets
      - name: "CH1_Data_RX_GPU"
        kind: "device"
        affinity: 0
        access:
          - local
        num_bufs: 10000
        # Size of the CHDR signal data packet (depends on number of samples transmitted)
        buf_size: 8192
      # Memory pool for channel 2 CHDR packet headers
      - name: "CH2_CHDR_Headers_RX_CPU"
        kind: "huge"
        affinity: 0
        access:
          - local
        num_bufs: 10000
        # Size of the CHDR header (depends on CHDR_W size)
        buf_size: 64
      # Memory pool for channel 2 CHDR signal data packets
      - name: "CH2_Data_RX_GPU"
        kind: "device"
        affinity: 0
        access:
          - local
        num_bufs: 10000
        # Size of the CHDR signal data packet (depends on number of samples transmitted)
        buf_size: 8192

    interfaces:
      - name: sdr_data
        # Set to the PCIe address of your ingest NIC.
        #  - See list with: sudo lshw -c network -businfo
        address: 0000:41:00.0
        rx:
          flow_isolation: true
          queues:
            - name: "Channel 1 data"
              id: 0
              cpu_core: 5
              # How many data packets do you want before
              # invoking the CHDR converter operator?
              # 20 data packets is 20480 samples and
              # we want 125 of them, so 2,500
              batch_size: 2500
              memory_regions:
                - "Headers_RX_CPU"
                - "CH1_CHDR_Headers_RX_CPU"
                - "CH1_Data_RX_GPU"
            - name: "Channel 2 data"
              id: 1
              cpu_core: 6
              # How many data packets do you want before
              # invoking the CHDR converter operator?
              # 20 data packets is 20480 samples and
              # we want 125 of them, so 2,500
              batch_size: 2500
              memory_regions:
                - "Headers_RX_CPU"
                - "CH2_CHDR_Headers_RX_CPU"
                - "CH2_Data_RX_GPU"

          flows:
            - name: "Channel 1 data packets"
              id: 0
              action:
                type: queue
                id: 0
              match:
                # Match with the port your SDR is sending to and the
                # length of the signal data packets
                udp_src: 49153
                udp_dst: 1234
                # ipv4_len: 4112
            - name: "Channel 2 data packets"
              id: 1
              action:
                type: queue
                id: 1
              match:
                # Match with the port your SDR is sending to and the
                # length of the signal data packets
                udp_src: 49153
                udp_dst: 1235
                # ipv4_len: 4112


chdr_converter:
  interface_name: sdr_data
  num_complex_samples_per_packet: 1024
  num_packets_per_fft: 20
  num_ffts_per_batch: 125
  num_simul_batches: 1
  num_channels: 2
  log_packets: false
  log_data: false

fft:
  burst_size: 20480
  num_bursts: 125
  num_channels: 2
  spectrum_type: 1
  averaging_type: 1
  window_time: 0
  window_type: 0
  transform_points: 20480
  window_points: 20480
  resolution: 1250
  span: 128000000
  weighting_factor: 0
  f1_index: -10240
  f2_index: 10239
  window_time_delta: 0

logger:
  num_channels: 2
  log_interval: 1
  log_data: false